backend:
  name: git-gateway
  repo: "mindas22/vegatestas-eglejura"
  branch: master # Branch to update (optional; defaults to master)
  site_domain: vegatestas-eglejura.com
# This line should *not* be indented
media_folder: "img"
public_folder: ".vuepress/dist/assets/img"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "/about/README.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "/konsultacija/README.md"
        label: "Konsultacija"
        name: "konsultacija"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "/vega-testas/README.md"
        label: "Vega Testas"
        name: "vegatestas"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "/README.md"
        label: "Pagrindinis puslapis"
        name: "pagrindinis puslapis"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
